apiVersion: apps/v1
kind: Deployment
metadata:
  name: vms-app
  labels:
    name: vms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vms-app
  template:
    metadata:
      labels:
        app: vms-app
    spec:
      containers:
      - name: vms-app
        image: gcr.io/erwindev-vms/vms-app:latest
        env:
        - name: FLASK_ENV
          value: "production"
        - name: SERVICE_NAME
          value: "Vendor Managetment Service"
        - name: CURRENT_VERSION
          value: "1.0-prod"
        - name: SECRET_KEY
          value: "my-guess-is-as-good-as-yours-but-you-will-never-guess-this%"                       
        - name: POSTGRES_DB
          value: "vms"
        - name: POSTGRES_HOST
          value: "localhost"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: vms-cloudsql-db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vms-cloudsql-db-credentials
              key: password
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        command: ["/cloud_sql_proxy",
          "-instances=erwindev-vms:us-east1:vms-app-db-01=tcp:5432",
          "-credential_file=/secrets/cloudsql/sql_credentials.json"]
        volumeMounts:
          - name: my-secrets-volume
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: my-secrets-volume
          secret:
            secretName: vms-cloudsql-instance-credentials