apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vms-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "vms-static-ip"  
spec:
  rules:
  - host: vms.erwindev.com
    http:
      paths:
      - backend:
          serviceName: vms-ui
          servicePort: 80   
  - host: vms-api.erwindev.com          
    http:
      paths:
      - backend:
          serviceName: vms-app
          servicePort: 5000           
