name: VMS application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        flask db upgrade
        export FLASK_ENV=test
        flask test
        coverage run vms_test_suite.py
        coverage report --fail-under=85 --omit="app/*/test/*.py" app/*/*/*.py

    - name: Setup gcloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        project_id: ${{ secrets.GCLOUD_PROJECT }}

    - name: Google Auth Docker
      run: |
        gcloud auth configure-docker 

    - name: Google Auth Container Cluster        
      run: |
        gcloud container clusters get-credentials vms-cluster --zone us-east1-b          
        
    - name: Build docker image
      run: |        
        docker build --file Dockerfile --tag gcr.io/${{ secrets.GCLOUD_PROJECT }}/vms-app:latest .
        
    - name: Publish docker image
      run: |
        docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/vms-app:latest

    - name: Deploy docker image to GKE
      run: |
        kubectl rollout restart deployment vms-app
